apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rx300zw20xpx3z4ln4fuzr3x9gtmw6fu32906fp2mv35g0crqffq75s3xs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVmJNT205ZjNld3Z2UENS
            c1NtZE14bTcrYUcybEc1TVFrUDEwUitxQVE0CkJiQ3hlK05TU2tIVUc2WWxML09O
            ZWNSVjdrcUVTVFVza2FiWTJCWURqdTAKLS0tIHJHLzNsaVBoUG1oeU9mYjBUT09P
            d3J6Wngwemx5RW5md1ZPNnhHeEQ1ZGcKqbKbYEZyaTaRBIjO9T/4JG2rjvnJE6ZI
            d6e5WRwoRat4wNEl2AMBSJ3SfxEomVlKGfKX/4IYO7GzSNWq1xDbzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T12:10:57Z"
    mac: ENC[AES256_GCM,data:O5fQKSnqZ0Wf1TMEz1JPT7qjL7qXdQ/Gm+mtfJs3SGOVA2DTf4yvIofULYlx15sYrZ4tTZkOlXcWPuZydORVcTsQpTD5dl4+mUN03czeFsv+dm5WoXvktKaAwY4e7VH6hIS9aXFVaWIOoNe71/Tvq8R8x3z1SpXQXrw38YIEwFM=,iv:24Z7Oetp2ecD856rrqNw2MrtiIO/0Ks8hH0k59hu1y0=,tag:8k86JqgBJ1gEqy8a5ggKig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: jetstack
    namespace: cert-manager
spec:
    interval: 1m
    url: https://charts.jetstack.io
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rx300zw20xpx3z4ln4fuzr3x9gtmw6fu32906fp2mv35g0crqffq75s3xs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVmJNT205ZjNld3Z2UENS
            c1NtZE14bTcrYUcybEc1TVFrUDEwUitxQVE0CkJiQ3hlK05TU2tIVUc2WWxML09O
            ZWNSVjdrcUVTVFVza2FiWTJCWURqdTAKLS0tIHJHLzNsaVBoUG1oeU9mYjBUT09P
            d3J6Wngwemx5RW5md1ZPNnhHeEQ1ZGcKqbKbYEZyaTaRBIjO9T/4JG2rjvnJE6ZI
            d6e5WRwoRat4wNEl2AMBSJ3SfxEomVlKGfKX/4IYO7GzSNWq1xDbzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T12:10:57Z"
    mac: ENC[AES256_GCM,data:O5fQKSnqZ0Wf1TMEz1JPT7qjL7qXdQ/Gm+mtfJs3SGOVA2DTf4yvIofULYlx15sYrZ4tTZkOlXcWPuZydORVcTsQpTD5dl4+mUN03czeFsv+dm5WoXvktKaAwY4e7VH6hIS9aXFVaWIOoNe71/Tvq8R8x3z1SpXQXrw38YIEwFM=,iv:24Z7Oetp2ecD856rrqNw2MrtiIO/0Ks8hH0k59hu1y0=,tag:8k86JqgBJ1gEqy8a5ggKig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    interval: 5m
    chart:
        spec:
            chart: cert-manager
            version: ^1
            sourceRef:
                kind: HelmRepository
                name: jetstack
                namespace: cert-manager
            interval: 1m
    values:
        installCRDs: true
        prometheus:
            enabled: true
            serviceMonitor:
                enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rx300zw20xpx3z4ln4fuzr3x9gtmw6fu32906fp2mv35g0crqffq75s3xs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVmJNT205ZjNld3Z2UENS
            c1NtZE14bTcrYUcybEc1TVFrUDEwUitxQVE0CkJiQ3hlK05TU2tIVUc2WWxML09O
            ZWNSVjdrcUVTVFVza2FiWTJCWURqdTAKLS0tIHJHLzNsaVBoUG1oeU9mYjBUT09P
            d3J6Wngwemx5RW5md1ZPNnhHeEQ1ZGcKqbKbYEZyaTaRBIjO9T/4JG2rjvnJE6ZI
            d6e5WRwoRat4wNEl2AMBSJ3SfxEomVlKGfKX/4IYO7GzSNWq1xDbzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T12:10:57Z"
    mac: ENC[AES256_GCM,data:O5fQKSnqZ0Wf1TMEz1JPT7qjL7qXdQ/Gm+mtfJs3SGOVA2DTf4yvIofULYlx15sYrZ4tTZkOlXcWPuZydORVcTsQpTD5dl4+mUN03czeFsv+dm5WoXvktKaAwY4e7VH6hIS9aXFVaWIOoNe71/Tvq8R8x3z1SpXQXrw38YIEwFM=,iv:24Z7Oetp2ecD856rrqNw2MrtiIO/0Ks8hH0k59hu1y0=,tag:8k86JqgBJ1gEqy8a5ggKig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:RqOVA5a8gMb0jKcDMeguBjRvhvJSfDMglFU71MvEIdIfWltF3uHTTw==,iv:IDybp6MEyXBVxod/EL2xgvX7ykfHJNZ8DPrWGxR5cs8=,tag:QpHJ7T8SXng4OP8oLpGrJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rx300zw20xpx3z4ln4fuzr3x9gtmw6fu32906fp2mv35g0crqffq75s3xs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVmJNT205ZjNld3Z2UENS
            c1NtZE14bTcrYUcybEc1TVFrUDEwUitxQVE0CkJiQ3hlK05TU2tIVUc2WWxML09O
            ZWNSVjdrcUVTVFVza2FiWTJCWURqdTAKLS0tIHJHLzNsaVBoUG1oeU9mYjBUT09P
            d3J6Wngwemx5RW5md1ZPNnhHeEQ1ZGcKqbKbYEZyaTaRBIjO9T/4JG2rjvnJE6ZI
            d6e5WRwoRat4wNEl2AMBSJ3SfxEomVlKGfKX/4IYO7GzSNWq1xDbzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T12:10:57Z"
    mac: ENC[AES256_GCM,data:O5fQKSnqZ0Wf1TMEz1JPT7qjL7qXdQ/Gm+mtfJs3SGOVA2DTf4yvIofULYlx15sYrZ4tTZkOlXcWPuZydORVcTsQpTD5dl4+mUN03czeFsv+dm5WoXvktKaAwY4e7VH6hIS9aXFVaWIOoNe71/Tvq8R8x3z1SpXQXrw38YIEwFM=,iv:24Z7Oetp2ecD856rrqNw2MrtiIO/0Ks8hH0k59hu1y0=,tag:8k86JqgBJ1gEqy8a5ggKig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: rupert@benbrook.org.uk
        privateKeySecretRef:
            name: letsencrypt
        solvers:
            - dns01:
                cloudflare:
                    email: rupert@benbrook.org.uk
                    apiTokenSecretRef:
                        name: cloudflare-api-token-secret
                        key: api-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rx300zw20xpx3z4ln4fuzr3x9gtmw6fu32906fp2mv35g0crqffq75s3xs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVmJNT205ZjNld3Z2UENS
            c1NtZE14bTcrYUcybEc1TVFrUDEwUitxQVE0CkJiQ3hlK05TU2tIVUc2WWxML09O
            ZWNSVjdrcUVTVFVza2FiWTJCWURqdTAKLS0tIHJHLzNsaVBoUG1oeU9mYjBUT09P
            d3J6Wngwemx5RW5md1ZPNnhHeEQ1ZGcKqbKbYEZyaTaRBIjO9T/4JG2rjvnJE6ZI
            d6e5WRwoRat4wNEl2AMBSJ3SfxEomVlKGfKX/4IYO7GzSNWq1xDbzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T12:10:57Z"
    mac: ENC[AES256_GCM,data:O5fQKSnqZ0Wf1TMEz1JPT7qjL7qXdQ/Gm+mtfJs3SGOVA2DTf4yvIofULYlx15sYrZ4tTZkOlXcWPuZydORVcTsQpTD5dl4+mUN03czeFsv+dm5WoXvktKaAwY4e7VH6hIS9aXFVaWIOoNe71/Tvq8R8x3z1SpXQXrw38YIEwFM=,iv:24Z7Oetp2ecD856rrqNw2MrtiIO/0Ks8hH0k59hu1y0=,tag:8k86JqgBJ1gEqy8a5ggKig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
