apiVersion: v1
kind: Namespace
metadata:
  name: trivy
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aqua
  namespace: trivy
spec:
  interval: 1m
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy
spec:
  interval: 5m
  chart:
    spec:
      chart: trivy-operator
      version: ^0
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy
      interval: 1m
  values: