apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ^40
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
      interval: 1m
  values: